[package]

name = "capnp"
version = "0.8.6"
authors = [ "David Renshaw <david@sandstorm.io>" ]
license = "MIT"
description = "runtime library for Cap'n Proto data encoding"
repository = "https://github.com/dwrensha/capnproto-rust"
documentation = "https://docs.capnproto-rust.org/capnp/"
homepage = "https://capnproto.org/"

readme = "README.md"

keywords = ["encoding", "protocol", "serialization"]
categories = ["encoding", "parser-implementations"]

[badges]
travis-ci = { repository = "dwrensha/capnproto-rust" }
appveyor = { repository = "dwrensha/capnproto-rust" }

[lib]

name = "capnp"
path = "src/lib.rs"

[dependencies]
byteorder = "1.0"
quickcheck = { version = "0.2", optional = true }

[dev-dependencies]
quickcheck = "0.2"

[features]
rpc = ["futures"]

[dependencies.futures]
version = "0.1"
optional = true
